// clang-format off

#define  RGB_BRIGHTNESS_UP    RGB_VAI
#define  RGB_BRIGHTNESS_DOWN  RGB_VAD

// Friendly names for the LED index corresponding to each physical key.
#define  LED_F5     5
#define  LED_F6     6
#define  LED_F7     7
#define  LED_F8     8
#define  LED_F9     9
#define  LED_F10   10
#define  LED_F11   11
#define  LED_F12   12
#define  LED_E     36
#define  LED_CAPS  50
#define  LED_S     52
#define  LED_D     53
#define  LED_F     54
#define  LED_LSFT  63
#define  LED_RSFT  74
#define  LED_LCTL  76
#define  LED_LGUI  77
#define  LED_LALT  78
#define  LED_RALT  80
#define  LED_RGUI  81
#define  LED_RCTL  83

// Four-character aliases for quantum keys.
#define  BOOT  QK_BOOTLOADER
#define  KMGC  LALT(KC_SYSTEM_REQUEST)
#define  H_FN  MO(FN)
#define  T_AC  QK_AUTOCORRECT_TOGGLE
#define  T_MC  TG(MEDIA)

// Four-character aliases for keycodes. Even the aliases which were already four
// characters are changed, to make them look more consistent.
#define  NONE  KC_NO
#define  ____  KC_TRANSPARENT
#define  _A__  KC_A
#define  _B__  KC_B
#define  _C__  KC_C
#define  _D__  KC_D
#define  _E__  KC_E
#define  _F__  KC_F
#define  _G__  KC_G
#define  _H__  KC_H
#define  _I__  KC_I
#define  _J__  KC_J
#define  _K__  KC_K
#define  _L__  KC_L
#define  _M__  KC_M
#define  _N__  KC_N
#define  _O__  KC_O
#define  _P__  KC_P
#define  _Q__  KC_Q
#define  _R__  KC_R
#define  _S__  KC_S
#define  _T__  KC_T
#define  _U__  KC_U
#define  _V__  KC_V
#define  _W__  KC_W
#define  _X__  KC_X
#define  _Y__  KC_Y
#define  _Z__  KC_Z
#define  _1__  KC_1
#define  _2__  KC_2
#define  _3__  KC_3
#define  _4__  KC_4
#define  _5__  KC_5
#define  _6__  KC_6
#define  _7__  KC_7
#define  _8__  KC_8
#define  _9__  KC_9
#define  _0__  KC_0
#define  ENT_  KC_ENTER
#define  ESC_  KC_ESCAPE
#define  BACK  KC_BACKSPACE
#define  TAB_  KC_TAB
#define  SPC_  KC_SPACE
#define  MINU  KC_MINUS
#define  EQL_  KC_EQUAL
#define  LBRC  KC_LEFT_BRACKET
#define  RBRC  KC_RIGHT_BRACKET
#define  BSLS  KC_BACKSLASH
#define  SEMI  KC_SEMICOLON
#define  QUOT  KC_QUOTE
#define  GRV_  KC_GRAVE
#define  COMM  KC_COMMA
#define  DOT_  KC_DOT
#define  SLSH  KC_SLASH
#define  CAPS  KC_CAPS_LOCK
#define  _F1_  KC_F1
#define  _F2_  KC_F2
#define  _F3_  KC_F3
#define  _F4_  KC_F4
#define  _F5_  KC_F5
#define  _F6_  KC_F6
#define  _F7_  KC_F7
#define  _F8_  KC_F8
#define  _F9_  KC_F9
#define  F10_  KC_F10
#define  F11_  KC_F11
#define  F12_  KC_F12
#define  PSCR  KC_PRINT_SCREEN
#define  SCRL  KC_SCROLL_LOCK
#define  INS_  KC_INSERT
#define  HOME  KC_HOME
#define  PGUP  KC_PAGE_UP
#define  DEL_  KC_DELETE
#define  END_  KC_END
#define  PGDN  KC_PAGE_DOWN
#define  RGHT  KC_RIGHT
#define  LEFT  KC_LEFT
#define  DOWN  KC_DOWN
#define  _UP_  KC_UP
#define  MUTE  KC_AUDIO_MUTE
#define  NEXT  KC_MEDIA_NEXT_TRACK
#define  PREV  KC_MEDIA_PREV_TRACK
#define  PLAY  KC_MEDIA_PLAY_PAUSE
#define  CALC  KC_CALCULATOR
#define  FWD_  KC_MEDIA_FAST_FORWARD
#define  REW_  KC_MEDIA_REWIND

// Because e.g. `LALT` is already used by QMK, these have an alternate "left/right" indicator.
#define  CTL_  KC_LEFT_CTRL
#define  SHF_  KC_LEFT_SHIFT
#define  ALT_  KC_LEFT_ALT
#define  GUI_  KC_LEFT_GUI
#define  _CTL  KC_RIGHT_CTRL
#define  _SHF  KC_RIGHT_SHIFT
#define  _ALT  KC_RIGHT_ALT
#define  _GUI  KC_RIGHT_GUI
